spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yumingkun/SpringCloudShopConfig
          username: yumingkun
          password:
          basedir: /Users/mingkunyu/Desktop/config/basebir
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest



server:
  port: 10000


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/






#用post 访问 http://localhost:10000/actuator/bus-refresh 可实现刷新配置
management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露全部路径

