server:
  port: 8000

spring:
  application:
    name: product
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weixin?autoReconnect=true
    username: root
    password: root


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/