spring:
  application:
    name: product
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG #配置中心在注册中心上的Application名字
      profile: dev


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/
